### PR TITLE
test: add various test cases from rules_nodejs

### PR DESCRIPTION
**Pull request by jbedard**
Fixes https://github.com/aspect-build/rules_jasmine/issues/8

# Description

Any other tests from rules_nodejs you think are worth adding? I'm not sure about the coverage tests, the bootstrap ones seem like basic node tests and not really specific to rules_jasmine?

### CODE REVIEW

**Comment by thesayyn** [comment]
maybe https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/jasmine/test/stack.spec.js too?

**Review by thesayyn — APPROVED** [review]

**Comment by jbedard** [comment]
Do you think the stack one applies here? Do you recall the original reason for it?

**Comment by thesayyn** [comment]
> Do you think the stack one applies here? Do you recall the original reason for it?

not really but seems important enough

**Comment by jbedard** [comment]
Note I did not add any of the coverage or node bootstrap-script tests since it seems like there is no logic for those in rules_jasmine. WDYT?

**Comment by thesayyn** [comment]
we dropped the support for boostrap-scripts. I am not sure if we should add support coverage here.

**Comment by thesayyn** [comment]
maybe it's okay to add the support for our generic js_test one here.

**Pull request merged**
